[project]
name = "behavior-senpai"
version = "1.4.0"
description = "A collection of Python scripts and applications for supporting Quantitative Behavioral Observation using videos."
readme = "README.md"
requires-python = "~=3.11.0"
dependencies = [
    "torch~=2.1.0",
    "mediapipe~=0.10.0",
    "scikit-learn~=1.4",
    "pyperclip~=1.9.0",
    "ttkthemes~=3.2",
    "numpy~=1.26",
    "pandas~=2.2",
    "seaborn~=0.13",
    "umap-learn>=0.5.6",
]
