[keypoints]
"nose" = {id=0, color=[40,40,255]}
"left_eye"= {id=1, color=[250,70,70]}
"right_eye"= {id=2, color=[50,250,50]}
"left_ear"= {id=3, color=[250,70,70]}
"right_ear"= {id=4, color=[50,250,50]}
"left_shoulder"= {id=5, color=[250,70,70]}
"right_shoulder"= {id=6, color=[50,250,50]}
"left_elbow"= {id=7, color=[250,70,70]}
"right_elbow"= {id=8, color=[50,250,50]}
"left_wrist"= {id=9, color=[250,70,70]}
"right_wrist"= {id=10, color=[50,250,50]}
"left_hip"= {id=11, color=[250,70,70]}
"right_hip"= {id=12, color=[50,250,50]}
"left_knee"= {id=13, color=[250,70,70]}
"right_knee"= {id=14, color=[50,250,50]}
"left_ankle"= {id=15, color=[250,70,70]}
"right_ankle"= {id=16, color=[50,250,50]}

[draw]
labels = ["nose", "left_shoulder", "right_shoulder"]
mask = ["nose", "left_ear", "right_ear", "left_eye", "right_eye"]

[bones]
bones = [
    ["left_shoulder", "right_shoulder"],
    ["left_shoulder", "left_hip"],
    ["right_shoulder", "right_hip"],
    ["left_shoulder", "left_elbow"],
    ["left_elbow", "left_wrist"],
    ["right_shoulder", "right_elbow"],
    ["right_elbow", "right_wrist"],
    ["left_hip", "right_hip"],
    ["left_hip", "left_knee"],
    ["left_knee", "left_ankle"],
    ["right_hip", "right_knee"],
    ["right_knee", "right_ankle"],
]

threshold = 0.4
